version: "3"
services:
  ehrbase:
    image: tornadoalert/ehrbase:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/medblocks_db
      - SPRING_DATASOURCE_USERNAME=medblocks_user
      - SPRING_DATASOURCE_PASSWORD=changeMePlease
      - SPRING_DATASOURCE_MAX_ACTIVE=20
      - SERVER_AQLCONFIG_USEJSQUERY=false
      - SERVER_NODENAME=ehrbase
      - SECURITY_AUTHTYPE=NONE
      - WEB_CORS_ALLOWEDORIGINPATTERNS=*
      - WEB_CORS_ALLOWEDMETHODS=GET,PUT,DELETE,POST,OPTIONS
      - WEB_CORS_ALLOWCREDENTIALS=true
      - ADMINAPI_ACTIVE=true
      - ADMINAPI_ALLOWDELETEALL=true
      - DB_USER_ADMIN=medblocks_user
      - DB_PASS_ADMIN=changeMePlease
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure
  db:
    image: postgres:13.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./createdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=changeMePlease
      - POSTGRES_USER=medblocks_user
      - POSTGRES_DB=medblocks_db
      - PGUSER=medblocks_user
      - PGPASSWORD=changeMePlease
      - PGDATABASE=medblocks_db
      - PGHOST=postgres

volumes:
  db-data:
